//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public decimal ID { get; set; }
        public decimal Department_ID { get; set; }
        public string Username { get; set; }
        public string Realname { get; set; }
        public string Password { get; set; }
        public Nullable<short> Roletype { get; set; }
        public Nullable<short> Seescope { get; set; }
        public Nullable<int> Logintimes { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
