//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public decimal ID { get; set; }
        public decimal Department_ID { get; set; }
        public string Username { get; set; }
        public string Realname { get; set; }
        public string Password { get; set; }
        public string Roletype { get; set; }
        public string Seescope { get; set; }
        public Nullable<int> Logintimes { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
