//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Admin = new HashSet<Admin>();
        }
    
        public decimal ID { get; set; }
        public string Department_Name { get; set; }
        public string Manager { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> Actualexpenses { get; set; }
        public Nullable<int> Estsalary { get; set; }
        public Nullable<int> Actualsalary { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Admin> Admin { get; set; }
    }
}
