//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.Rolefunctions = new HashSet<Rolefunctions>();
        }
    
        public decimal ID { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Rolefunctions> Rolefunctions { get; set; }
    }
}
