//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public decimal ID { get; set; }
        public int Senderid { get; set; }
        public int Receiverid { get; set; }
        public string Sendername { get; set; }
        public string Receivername { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    }
}
