//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public Notice()
        {
            this.Usernotice = new HashSet<Usernotice>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> Noticetype { get; set; }
        public string Title { get; set; }
        public string Notice_Content { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Usernotice> Usernotice { get; set; }
    }
}
