//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public Notice()
        {
            this.Usernotices = new HashSet<Usernotice>();
        }
    
        public System.Guid ID { get; set; }
        public string Noticetype { get; set; }
        public string Title { get; set; }
        public string Notice_Content { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Usernotice> Usernotices { get; set; }
    }
}
