//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public Notice()
        {
            this.Usernotice = new HashSet<Usernotice>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NoticeType { get; set; }
        public string Title { get; set; }
        public string Notice_Content { get; set; }
        public Nullable<System.DateTime> CommitTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<Usernotice> Usernotice { get; set; }
    }
}
