//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blogs = new HashSet<Blog>();
            this.Comments = new HashSet<Comment>();
            this.Logusers = new HashSet<Loguser>();
            this.Msgs = new HashSet<Msg>();
            this.Msgs1 = new HashSet<Msg>();
            this.Userdetails = new HashSet<Userdetail>();
            this.Usernotices = new HashSet<Usernotice>();
            this.Userroles = new HashSet<Userrole>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid Department_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Loguser> Logusers { get; set; }
        public virtual ICollection<Msg> Msgs { get; set; }
        public virtual ICollection<Msg> Msgs1 { get; set; }
        public virtual ICollection<Userdetail> Userdetails { get; set; }
        public virtual ICollection<Usernotice> Usernotices { get; set; }
        public virtual ICollection<Userrole> Userroles { get; set; }
    }
}
