//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usernotice
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Notice_ID { get; set; }
        public Nullable<System.DateTime> CommitTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Notice Notice { get; set; }
        public virtual User User { get; set; }
    }
}
