//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blog = new HashSet<Blog>();
            this.Comment = new HashSet<Comment>();
            this.Loguser = new HashSet<Loguser>();
            this.Userdetail = new HashSet<Userdetail>();
            this.Usernotice = new HashSet<Usernotice>();
            this.Userrole = new HashSet<Userrole>();
        }
    
        public decimal ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public Nullable<System.DateTime> Logintimes { get; set; }
        public Nullable<System.DateTime> Committime { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    
        public virtual ICollection<Blog> Blog { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Loguser> Loguser { get; set; }
        public virtual ICollection<Userdetail> Userdetail { get; set; }
        public virtual ICollection<Usernotice> Usernotice { get; set; }
        public virtual ICollection<Userrole> Userrole { get; set; }
    }
}
